name: Atualizar Lista FILMES LINK DIRETO

on:
  schedule:
    - cron: '0 1 * * *'  # Executa todos os dias à 01:00
  workflow_dispatch:

jobs:
  atualizar-lista:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Baixar lista .m3u original
        run: |
          curl -L -o lista.m3u "http://cdn.pthdtv.top:80/get.php?username=630922725&password=280890306&type=m3u_plus&output=mpegts"

      - name: Filtrar e ordenar grupos EXATOS (sem EPG)
        run: |
          grupos=(
            "LANÇAMENTOS 2025"
            "LANÇAMENTOS 2024"
            "LANÇAMENTOS 2023"
            "LANÇAMENTOS 2022"
            "FILMES | LEGENDADOS"
            "FILMES DRAMA"
            "FILMES ROMANCE"
            "FILMES TERROR"
            "FILMES AÇÃO"
            "FILMES FICÇÃO"
            "FILMES AVENTURA"
            "FILMES FANTASIA"
            "FILMES | 4K"
            "FILMES SUSPENSE"
            "FILMES NACIONAL"
            "FILMES GUERRA"
            "FILMES PRIME VIDEO"
            "FILMES ANIMAÇÃO"
            "FILMES COMÉDIA"
            "FILMES DOCUMENTÁRIOS"
            "FILMES FAROESTE"
            "FILMES NETFLIX"
            "FILMES INFANTIL"
            "FILMES ANIME"
            "FILMES DISNEY+"
            "FILMES APPLE TV+"
            "FILMES GLOBOPLAY"
            "FILMES PARAMOUNT+"
            "FILMES HBO MAX"
            "FILMES STAR+"
            "FILMES CRIME"
            "FILMES | COPA DO MUNDO 2022"
            "FILMES RELIGIOSOS"
            "FILMES BRASIL PARALELO"
            "FILMES | DESPERTAR UMA NOVA CONSCIÊNCIA"
            "FILMES | SONS PARA DORMIR"
            "FILMES DC COMICS"
            "FILMES MARVEL"
            "FILMES | 007 COLEÇÃO"
          )

          echo "#EXTM3U" > filmes.txt

          for grupo in "${grupos[@]}"; do
            awk -v grupo="$grupo" '
              BEGIN { IGNORECASE = 0 }
              $0 ~ "group-title=\"" grupo "\"" {
                getline url
                print $0 RS url
              }
            ' lista.m3u >> filmes.txt
          done

          mv filmes.txt "BluePlay/FILMES/LINK DIRETO/FILMES.txt"

      - name: Criar backup
        run: |
          mkdir -p "BluePlay/FILMES/LINK DIRETO/backup"
          cp "BluePlay/FILMES/LINK DIRETO/FILMES.txt" "BluePlay/FILMES/LINK DIRETO/backup/FILMES_$(date +'%Y-%m-%d_%H-%M').txt"

      - name: Configurar Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Verificar alterações
        run: |
          git add "BluePlay/FILMES/LINK DIRETO/FILMES.txt"
          git commit -m "Atualização automática da lista FILMES LINK DIRETO" || echo "Sem alterações"

      - name: Enviar alterações
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: main
