name: Atualizar TV AO VIVO

on:
  schedule:
    - cron: '0 3 * * *'  # Executa todos os dias às 03h UTC (00h Brasília)
  workflow_dispatch:  # Permite execução manual

jobs:
  atualizar-lista:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Baixar a lista completa
        run: |
          curl -L -o lista.m3u "LINK-DA-SUA-M3U"

      - name: Filtrar grupos desejados
        run: |
          grep -E 'group-title="(24H SÉRIES|24H DESENHOS|FILMES E SÉRIES|⭐ REALITY BBB 2025|ABERTOS|DOCUMENTÁRIOS|BAND|NOTÍCIAS|VARIEDADES|RELIGIOSOS|INFANTIL|SKY PLAY|DISCOVERY|DISNEY\+ \| HBO MAX|24H SHOWS|GLOBOS REGIONAIS|GLOBOS CAPITAIS|REDE HBO|RECORD TV|SBT|REDE TELECINE)"' -A1 lista.m3u > "BluePlay/TV AO VIVO/CANAIS AO VIVO/TV AO VIVO.txt"

      - name: Configurar Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Fazer commit e push
        run: |
          git add "BluePlay/TV AO VIVO/CANAIS AO VIVO/TV AO VIVO.txt"
          git commit -m "Atualização automática da lista TV AO VIVO" || exit 0
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/BluePlay8486/BluePlayHD.git HEAD:main
