name: Atualizar TV AO VIVO.txt diariamente

on:
  schedule:
    - cron: '0 2 * * *'  # Executa todo dia às 02h UTC
  workflow_dispatch:

jobs:
  atualizar-tv-ao-vivo:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Baixar lista M3U completa
        run: |
          curl -s -o lista.m3u "http://cdn.pthdtv.top:80/get.php?username=630922725&password=280890306&type=m3u_plus"
          head -n 10 lista.m3u  # Verificar se baixou certo

      - name: Filtrar grupos desejados e atualizar TV AO VIVO.txt
        run: |
          grep -Ei 'group-title=".*(24H|FILMES|REALITY|ABERTOS|DOCUMENT|BAND|NOT[IÍ]CIAS|VARIEDADES|RELIGIOSOS|INFANTIL|SKY|DISCOVERY|DISNEY|HBO|SHOWS|GLOBOS|RECORD|SBT|TELECINE).*"' -A1 lista.m3u > "BluePlay/TV AO VIVO/CANAIS AO VIVO/TV AO VIVO.txt"

      - name: Commitar alterações
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add "BluePlay/TV AO VIVO/CANAIS AO VIVO/TV AO VIVO.txt"
          git commit -m "Atualização automática da lista TV AO VIVO" || true
          git push || true
