name: Gerar ESPORTES.xml

on:
  workflow_dispatch:  # Executar manualmente pelo GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install requests

      - name: Executar script Python
        run: python gerar_esportes.py

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Adicionar ESPORTES.xml
        run: git add "BluePlay/TV AO VIVO/ESPORTES/ESPORTES.xml"

      - name: Commitar alterações
        run: |
          git commit -m "Atualização automática do ESPORTES.xml" || echo "Nenhuma alteração para commitar"

      - name: Enviar alterações
        run: git push
