name: Atualizar TV AO VIVO.txt a cada 24h

on:
  schedule:
    - cron: '0 3 * * *'  # Executa todo dia às 03h UTC (00h horário de Brasília)
  workflow_dispatch:     # Também pode rodar manualmente

jobs:
  atualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Baixar a lista M3U original
        run: curl -L -o lista.m3u "http://cdn.pthdtv.top:80/get.php?username=630922725&password=280890306&type=m3u_plus&output=mpegts"

      - name: Filtrar os grupos desejados
        run: |
          grep -E 'group-title="(24H SÉRIES|24H DESENHOS|FILMES E SÉRIES|⭐ REALITY BBB 2025|ABERTOS|DOCUMENTÁRIOS|BAND|NOTÍCIAS|VARIEDADES|RELIGIOSOS|INFANTIL|SKY PLAY|DISCOVERY|DISNEY\+ \| HBO MAX|24H SHOWS|GLOBOS REGIONAIS|GLOBOS CAPITAIS|REDE HBO|RECORD TV|SBT|REDE TELECINE)"' -A1 lista.m3u > "BluePlay/TV AO VIVO/CANAIS AO VIVO/TV AO VIVO.txt"

      - name: Configurar Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Fazer commit e push
        run: |
          git add "BluePlay/TV AO VIVO/CANAIS AO VIVO/TV AO VIVO.txt"
          git commit -m "Atualização automática da lista TV AO VIVO" || echo "Sem alterações"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main || true
