name: Atualizar TV AO VIVO

on:
  schedule:
    - cron: '0 0 * * *'  # Executa a cada 24h (00:00 UTC)
  workflow_dispatch:     # Permite rodar manualmente

jobs:
  atualizar-lista:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Instalar dependências
      run: sudo apt-get update && sudo apt-get install -y grep

    - name: Baixar lista M3U
      run: |
        curl -L -o lista.m3u "https://raw.githubusercontent.com/BluePlay8486/BluePlayHD/main/BluePlay/TV%20AO%20VIVO/CANAIS%20AO%20VIVO/TV%20AO%20VIVO.m3u"

    - name: Filtrar grupos desejados
      run: |
        grep -E 'group-title="(24H SÉRIES|24H DESENHOS|FILMES E SÉRIES|⭐ REALITY BBB 2025|ABERTOS|DOCUMENTÁRIOS|BAND|NOTÍCIAS|VARIEDADES|RELIGIOSOS|INFANTIL|SKY PLAY|DISCOVERY|DISNEY\+ \| HBO MAX|24H SHOWS|GLOBOS REGIONAIS|GLOBOS CAPITAIS|REDE HBO|RECORD TV|SBT|REDE TELECINE)"' -A1 lista.m3u > "BluePlay/TV AO VIVO/CANAIS AO VIVO/TV AO VIVO.txt" || echo "Nada encontrado"

    - name: Verificar mudanças
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add "BluePlay/TV AO VIVO/CANAIS AO VIVO/TV AO VIVO.txt"
        git diff --cached --quiet || git commit -m "Atualização automática da lista TV AO VIVO"
        git push
