name: Atualizar Filmes XML

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  gerar-filmes:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar dependências Python
        run: pip install requests

      - name: Executar o script de geração do XML
        run: python gerar_filmes.py

      - name: Commitar e enviar alterações
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull --rebase --autostash
          git add BluePlay/FILMES/LINK\ DIRETO/FILMES.xml
          git commit -m "Atualização automática do FILMES.xml" || echo "Sem alterações"
          git push
