name: Atualizar Lista TV AO VIVO

on:
  schedule:
    - cron: '0 0 * * *'  # Executa todos os dias à meia-noite
  workflow_dispatch:

jobs:
  atualizar-lista:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar repositório
      - name: Clonar repositório
        uses: actions/checkout@v3

      # 2. Baixar lista .m3u original
      - name: Baixar lista .m3u original
        run: |
          curl -L -o lista.m3u "http://cdn.pthdtv.top:80/get.php?username=630922725&password=280890306&type=m3u_plus&output=mpegts"

      # 3. Filtrar canais desejados
      - name: Filtrar canais desejados (ignora emojis, acentos e caixa)
        run: |
          awk '
          BEGIN {
            IGNORECASE = 1
            split("24h series 24h desenhos filmes e series reality bbb abertos documentarios band noticias variedades religiosos infantil sky play discovery disney hbo max 24h shows globos regionais globos capitais rede hbo record tv sbt rede telecine", grupos, " ")
            for (i in grupos) alvo[grupos[i]] = 1
          }
          function normalize(str) {
            gsub(/[[:punct:][:cntrl:][:space:]]/, "", str)
            gsub(/[áàãâä]/, "a", str)
            gsub(/[éèêë]/, "e", str)
            gsub(/[íìîï]/, "i", str)
            gsub(/[óòõôö]/, "o", str)
            gsub(/[úùûü]/, "u", str)
            gsub(/[ç]/, "c", str)
            return tolower(str)
          }
          /#EXTINF/ {
            line = $0
            match($0, /group-title="([^"]+)"/, arr)
            grupo = normalize(arr[1])
            for (g in alvo) {
              if (grupo ~ g) {
                print line
                getline
                print
                break
              }
            }
          }' lista.m3u > "BluePlay/TV AO VIVO/CANAIS AO VIVO/TV AO VIVO.txt"

      # 4. Criar backup da lista (opcional, caso queira manter versões)
      - name: Criar backup da lista
        run: |
          mkdir -p "BluePlay/TV AO VIVO/backup"
          cp "BluePlay/TV AO VIVO/CANAIS AO VIVO/TV AO VIVO.txt" "BluePlay/TV AO VIVO/backup/TV_$(date +'%Y-%m-%d_%H-%M').txt"

      # 5. Configurar Git
      - name: Configurar Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      # 6. Verificar alterações
      - name: Verificar alterações
        run: |
          git add "BluePlay/TV AO VIVO/CANAIS AO VIVO/TV AO VIVO.txt"
          git commit -m "Atualização automática da lista TV AO VIVO" || echo "Sem alterações"

      # 7. Enviar alterações
      - name: Enviar alterações
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}  # Usando o GH_TOKEN como secret
          branch: main
