name: Atualizar ESPORTES

on:
  push:
    paths:
      - 'Atualizar_TV.AO.VIVO.yml'
      - 'gerar_esportes.py'

jobs:
  gerar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          pip install pyyaml requests

      - name: Executar script Python
        run: python gerar_esportes.py

      - name: Commitar ESPORTES.txt gerado
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ESPORTES.txt
          git commit -m "Atualizar ESPORTES.txt via workflow" || echo "Sem mudanças"
          git push
