name: Gerar XML de Filmes

on:
  workflow_dispatch:
  push:
    paths:
      - 'lista.m3u'
      - 'converter_m3u_filmes_para_xml.py'
  schedule:
    - cron: '0 */6 * * *'  # Executa a cada 6 horas

jobs:
  gerar-xml:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Executar script de conversão M3U para XML
        run: python converter_m3u_para_xml.py

      - name: Confirmar alterações
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add BluePlay/FILMES/LINK\ DIRETO/FILMES.txt
          git commit -m "Atualização automática do XML de filmes via GitHub Actions" || echo "Nenhuma alteração para commitar"

      - name: Enviar para o repositório
        run: git push
