name: Atualizar TV AO VIVO

on:
  schedule:
    - cron: '0 3 * * *'  # Executa todo dia às 03:00 da manhã (horário UTC)
  workflow_dispatch:      # Permite executar manualmente pelo GitHub

jobs:
  atualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Baixar lista original
        run: curl -o lista_original.m3u "http://cdn.pthdtv.top:80/get.php?username=630922725&password=280890306&type=m3u_plus&output=mpegts"

      - name: Filtrar grupos desejados
        run: |
          grupos=(
            "24H SÉRIES"
            "24H DESENHOS"
            "FILMES E SÉRIES"
            "⭐REALITY BBB 2025"
            "ABERTOS"
            "DOCUMENTÁRIOS"
            "BAND"
            "NOTÍCIAS"
            "VARIEDADES"
            "RELIGIOSOS"
            "INFANTIL"
            "SKY PLAY"
            "DISCOVERY"
            "DISNEY+|HBO MAX"
            "24H SHOWS"
            "GLOBOS REGIONAIS"
            "GLOBOS CAPITAIS"
            "REDE HBO"
            "RECORD TV"
            "SBT"
            "REDE TELECINE"
          )

          echo "#EXTM3U" > canais_filtrados.m3u

          salvar="false"
          while IFS= read -r linha; do
            if [[ "$linha" == *"#EXTINF"* ]]; then
              grupo=$(echo "$linha" | grep -oP 'group-title=".*?"' | cut -d'"' -f2)
              if printf '%s\n' "${grupos[@]}" | grep -Fxq "$grupo"; then
                salvar="true"
              else
                salvar="false"
              fi
            fi

            if [[ "$salvar" == "true" ]]; then
              echo "$linha" >> canais_filtrados.m3u
            fi
          done < lista_original.m3u

      - name: Substituir TV AO VIVO.txt
        run: |
          cp canais_filtrados.m3u "BluePlay/TV AO VIVO/CANAIS AO VIVO/TV AO VIVO.txt"

      - name: Commit e push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "BluePlay/TV AO VIVO/CANAIS AO VIVO/TV AO VIVO.txt"
          git commit -m "Atualização automática dos canais ao vivo"
          git push
