name: Atualizar FILMES.xml

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Executa a cada 6 horas

jobs:
  gerar-filmes-xml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        pip install --upgrade pip
        pip install -r src/requirements.txt

    - name: Executar script para gerar FILMES.xml
      run: python src/main.py

    - name: Verificar se o XML foi gerado
      run: |
        if [ ! -f BluePlay/FILMES/LINK DIRETO/FILMES.xml ]; then
          echo "Arquivo FILMES.xml não encontrado!"
          exit 1
        fi

    - name: Fazer upload do artefato FILMES.xml
      uses: actions/upload-artifact@v3
      with:
        name: FILMES.xml
        path: BluePlay/FILMES/LINK DIRETO/FILMES.xml
