name: Atualizar Filmes XML

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Executa a cada 6 horas

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          cd src
          pip install -r requirements.txt

      - name: Executar script principal
        run: |
          cd src
          python main.py

      - name: Upload do XML gerado
        uses: actions/upload-artifact@v4
        with:
          name: filmes-xml
          path: BluePlay/FILMES/LINK DIRETO/FILMES.xml
