name: Gerar XML de Filmes

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Executa a cada 6 horas

jobs:
  gerar-xml:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: pip install requests

      - name: Executar script de conversão
        run: python converter_m3u_para_xml.py

      - name: Commit e push do XML gerado
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add BluePlay/FILMES/LINK\ DIRETO/FILMES.txt
          git commit -m "Atualização automática do FILMES.txt via workflow"
          git push
