name: Gerar XML de Filmes

on:
  workflow_dispatch:

jobs:
  gerar-filmes-xml:
    runs-on: ubuntu-latest

    steps:
    - name: '[SUCESSO] Clonando o repositório'
      uses: actions/checkout@v3

    - name: '[SUCESSO] Configurando Python'
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: '[SUCESSO] Instalando dependências'
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: '[SUCESSO] Executando o script para gerar o XML'
      run: |
        python3 gerar_filmes.py

    - name: '[VALIDAÇÃO] Verificando se o XML foi gerado'
      run: |
        if [ -f "BluePlay/FILMES/LINK DIRETO/FILMES.xml" ]; then
          echo "[SUCESSO] O arquivo XML foi gerado com sucesso."
        else
          echo "[ERRO] O arquivo XML NÃO foi gerado."
          exit 1
        fi

    - name: '[SUCESSO] Fazendo upload do XML gerado'
      uses: actions/upload-artifact@v2.3.1
      with:
        name: filmes_xml
        path: BluePlay/FILMES/LINK DIRETO/FILMES.xml
