name: Gerar XML de Filmes

on:
  workflow_dispatch:

jobs:
  gerar_xml:
    name: Gerar e exportar XML de Filmes
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install requests

      - name: Executar o script Python
        run: python converter_m3u_filmes1.py

      - name: Verificar se o XML foi gerado
        run: |
          if [ ! -f "BluePlay/FILMES/LINK DIRETO/FILMES.xml" ]; then
            echo "Arquivo XML não foi gerado."
            exit 1
          fi

      - name: Upload do XML como artefato
        uses: actions/upload-artifact@v3
        with:
          name: filmes-xml
          path: BluePlay/FILMES/LINK DIRETO/FILMES.xml
