name: Gerar XML de Filmes

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install requests

      - name: Executar script para gerar XML
        run: python3 converter_m3u_para_xml.py

      - name: Verificar se o XML foi gerado
        run: |
          if [ ! -f "BluePlay/FILMES/LINK DIRETO/FILMES.xml" ]; then
            echo "Erro: XML não encontrado!"
            exit 1
          fi

      - name: Upload do arquivo XML gerado
        uses: actions/upload-artifact@v2
        with:
          name: filmes_xml
          path: BluePlay/FILMES/LINK DIRETO/FILMES.xml
