name: Gerar XML a partir da M3U

on:
  workflow_dispatch:  # Permite rodar manualmente via GitHub Actions
  push:
    paths:
      - 'converter_m3u_para_xml.py'
      - '.github/workflows/gerar_xml.yml'
      - 'requirements.txt'

jobs:
  gerar-xml:
    name: Gerar Arquivo XML
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Verificar e instalar dependências
        run: |
          echo "Verificando requirements.txt..."
          if [ -f requirements.txt ]; then
            echo "Instalando dependências..."
            pip install -r requirements.txt
          else
            echo "Arquivo requirements.txt não encontrado, pulando instalação."
          fi

      - name: Executar script Python para gerar XML
        run: |
          echo "Executando script de conversão..."
          python3 converter_m3u_para_xml.py

      - name: Verificar se o arquivo XML foi gerado
        run: |
          if [ ! -f "./BluePlay/FILMES/LINK DIRETO/FILMES.txt" ]; then
            echo "ERRO: Arquivo FILMES.txt não encontrado!"
            exit 1
          else
            echo "Arquivo FILMES.txt gerado com sucesso!"
          fi

      - name: Fazer upload do XML gerado como artefato
        uses: actions/upload-artifact@v2
        with:
          name: Filmes_XML
          path: './BluePlay/FILMES/LINK DIRETO/FILMES.txt'
