name: Atualizar EPG.xml a cada 12 horas

on:
  schedule:
    - cron: '0 */12 * * *'  # Atualiza a cada 12 horas (00h e 12h UTC)
  workflow_dispatch:         # Permite rodar manualmente no GitHub

jobs:
  atualizar-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Baixar EPG.xml
        run: |
          curl -o epg.xml "http://cdn.pthdtv.top:80/xmltv.php?username=630922725&password=280890306"

- name: Commitar alterações
  run: |
    git config user.name "github-actions"
    git config user.email "github-actions@users.noreply.github.com"
    git add epg.xml
    git commit -m "Atualização automática do EPG.xml" || true
    git push || true
