name: Atualizar EPG.xml a cada 12 horas

on:
  schedule:
    - cron: '0 */12 * * *'  # Executa a cada 12 horas (00h e 12h UTC)
  workflow_dispatch:         # Permite execução manual

jobs:
  atualizar-epg:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar o repositório
      - name: Clonar o repositório
        uses: actions/checkout@v3

      # 2. Baixar EPG.xml
      - name: Baixar EPG.xml
        run: |
          echo "Baixando epg.xml..."
          curl -L -o epg.xml "http://cdn.pthdtv.top:80/xmltv.php?username=630922725&password=280890306"

      # 3. Verificar se o arquivo foi baixado
      - name: Verificar tamanho do EPG.xml
        run: |
          if [ -f "epg.xml" ]; then
            echo "Arquivo baixado com sucesso:"
            ls -lh epg.xml
          else
            echo "Erro: epg.xml não foi baixado."
            exit 1
          fi

      # 4. Mostrar as 10 primeiras linhas (opcional para ver se tem conteúdo válido)
      - name: Mostrar conteúdo inicial do EPG.xml
        run: head -n 10 epg.xml || true

      # 5. Configurar Git
      - name: Configurar Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      # 6. Commitar alterações se houver diferença
      - name: Commitar alterações
        run: |
          git add epg.xml
          git diff --cached --quiet || git commit -m "Atualização automática do EPG.xml"

      # 7. Enviar alterações
      - name: Push para o repositório
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
