name: Atualizar EPG.xml diariamente

on:
  schedule:
    - cron: '0 3 * * *'  # Executa todo dia às 03:00 (UTC)
  workflow_dispatch:     # Permite rodar manualmente

jobs:
  atualizar-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Baixar EPG.xml
        run: |
          curl -o epg.xml https://URL-DA-SUA-EPG.COM/epg.xml

      - name: Commitar alterações
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add epg.xml
          git commit -m "Atualização automática do EPG.xml"
          git push
